### PR TITLE
mkinitcpio: Fix --cmdline and --osrelease, add them to _opt_long

### PR DESCRIPTION
**Pull request by jirutka**
Fixes https://github.com/archlinux/mkinitcpio/pull/53#discussion_r667359644.

### CODE REVIEW

**Comment by Foxboron** [comment]
They are fixed in my followup pull-request https://github.com/archlinux/mkinitcpio/pull/58

**Comment by jirutka** [comment]
Closing as duplicate of #58.

**Comment by jirutka** [comment]
@Foxboron, mea culpa, I forgot to check existing PRs before opening this one.

**Comment by Foxboron** [comment]
No problem :) Thanks for the review and feedback regardless!

**Pull request closed without merging**
